In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.api as sm

In [11]:
df = pd.read_excel('Данные для тестового задания.xlsx', sheet_name='Данные АБ тестов')
df.head()

   experiment_num experiment_group   user_id  revenue
0               1             test     38456      520
1               1          control  13125924      806
2               1          control   9761984        0
3               1             test  11387012      208
4               1             test  18319648      104

In [13]:
# 8 задание

for exp in df['experiment_num'].unique():
  c = df[(df['experiment_num'] == exp) & (df['experiment_group'] == 'control')][
      'revenue'
  ]
  t = df[(df['experiment_num'] == exp) & (df['experiment_group'] == 'test')][
      'revenue'
  ]
  if len(t) > 0:
    stat, pval = stats.ttest_ind(c, t, equal_var=False)
    print(f'Эксперимент {exp}: p-value = {pval:.4f}')
  else:
    print(f'Эксперимент {exp}: нет тестовой группы')

Эксперимент 1: p-value = 0.6890
Эксперимент 2: p-value = 0.0011
Эксперимент 3: p-value = 0.0603

In [16]:
# 9 задание
df_listers = pd.read_excel('Данные для тестового задания.xlsx', sheet_name='Листеры')
df_listers.head()

   user_id       date  cnt_adverts  age  cnt_contacts  revenue
0      100 2022-01-01            6   21           119       53
1      100 2022-01-02            2   21           200       18
2      100 2022-01-03            6   21           193       42
3      100 2022-01-04            2   21           143       38
4      100 2022-01-05            2   21           190       40

In [18]:
mean_income = df_listers['revenue'].mean()
print(f'Средний доход: {mean_income}')

Средний доход: 30.70253164556962

In [19]:
# 10 задание
median_age = df_listers['age'].median()
print(f'Медиана возраста: {median_age}')

Медиана возраста: 28.0

In [21]:
# 18 задание

# посетители и плательщики группы А
visitors_a = 100047501
conversions_a = 1003

# посетители и плательщики группы B
visitors_b = 100001055
conversions_b = 1099

# Z тест для двух долей
count = np.array([conversions_b, conversions_a])
nobs = np.array([visitors_b, visitors_a])

z_stat, p_value = sm.stats.proportions_ztest(count, nobs)

print(f'p-value: {p_value:.5f}')

p-value: 0.03533